### ISSUE TITLE
Drupal 8.5

### ISSUE THREAD

**Issue by Resistant-X** [leymannx/image_first_formatter#1]
I can install the module without any problems. But nowhere to find / adjust Image Formater (Content Type -> Manage Display) or in Views. Am I doing something wrong or is it because of the version

**Comment by leymannx** [comment]
Let me have a look at this later. I'll keep you informed about my findings.

**Comment by leymannx** [comment]
Sorry can't reproduce. For me it's working fine in a freshly installed D8 instance.

![screenshot 2018-03-18 19 39 48](https://user-images.githubusercontent.com/3585653/37569555-3c55de1e-2ae4-11e8-9744-168eebbffa0c.png)

**Comment by leymannx** [comment]
![screenshot 2018-03-18 19 43 11](https://user-images.githubusercontent.com/3585653/37569577-b80a602a-2ae4-11e8-87e6-0e39a981f0d4.png)

**Comment by resi23** [comment]
Mysterious I uninstalled and reinstalled it. Now everything is fine. Sorry for the trouble.

**Comment by normanlolx** [comment]
Thanks for reaching back. Maybe it was just a caching issue.
